import 'package:project_manager/data/models/priority_level.dart';
import 'package:project_manager/data/models/project.dart';
import 'package:project_manager/data/models/status.dart';
import 'package:project_manager/data/repositories/project_repository.dart';

class ProjectService {
  final ProjectRepository _repository;

  /// Constructor - takes repository as dependency
  /// This is "dependency injection" - service doesn't care which implementation
  ProjectService(this._repository);

  /// Create project with auto-generated ID
  /// Business logic: Generate ID, set timestamps
  Project createProject({
    required String name,
    String? description,
    DateTime? deadline,
    String? categoryId,
    ProjectStatus? status,
    PriorityLevel? priority,
    List<String>? tags,
  }) {
    // Generate ID (simple counter for MVP)
    // Should ID be generated by the backend instead?
    final id = DateTime.now().millisecondsSinceEpoch.toString();

    final project = Project(
      id: id,
      name: name,
      description: description,
      categoryId: categoryId ?? '1',
      status: status ?? ProjectStatus.notStarted,
      deadline: deadline,
      priority: priority ?? PriorityLevel.no,
      tags: tags,
      updatedAt: DateTime.now(),
    );

    return _repository.create(project);
  }

  List<Project> getAllProjects() {
    return _repository.getAll();
  }

  // Project? getProjectById(String id) {
  //   return _repository.getById(id);
  // }

  /// Update project
  Project updateProject(Project project) {
    final updated = Project(
      id: project.id,
      name: project.name,
      description: project.description,
      categoryId: project.categoryId,
      tags: project.tags,
      status: project.status,
      priority: project.priority,
      deadline: project.deadline,
      updatedAt: DateTime.now(),
    );
    return _repository.update(updated);
  }

  // /// Delete project
  // bool deleteProject(String id) {
  //   return _repository.delete(id);
  // }

  // /// Business logic: Get ongoing projects
  // List<Project> getOngoingProjects() {
  //   return _repository
  //       .getAll()
  //       .where((p) => p.status == ProjectStatus.ongoing)
  //       .toList();
  // }

  // /// Business logic: Get upcoming deadlines (next 1 month)
  // List<Project> getUpcomingDeadlines() {
  //   final now = DateTime.now();
  //   final oneMonthFromNow = now.add(Duration(days: 30));

  //   return _repository
  //       .getAll()
  //       .where(
  //         (p) =>
  //             p.deadline.isAfter(now) && p.deadline.isBefore(oneMonthFromNow),
  //       )
  //       .toList()
  //     ..sort((a, b) => a.deadline.compareTo(b.deadline));
  // }
}
